pub mod curbed_recency_proportional;
pub mod depth_proportional;
pub mod depth_proportional_tapered;
pub mod dynamic;
pub mod fixed_resolution;
pub mod geometric_seq_nth_root;
pub mod geometric_seq_nth_root_tapered;
pub mod nominal_resolution;
pub mod perfect_resolution;
pub mod pseudostochastic;
pub mod recency_proportional;
pub mod stochastic;
mod r#trait;

pub use curbed_recency_proportional::CurbedRecencyProportionalPolicy;
pub use depth_proportional::DepthProportionalPolicy;
pub use depth_proportional_tapered::DepthProportionalTaperedPolicy;
pub use dynamic::DynamicPolicy;
pub use fixed_resolution::FixedResolutionPolicy;
pub use geometric_seq_nth_root::GeometricSeqNthRootPolicy;
pub use geometric_seq_nth_root_tapered::GeometricSeqNthRootTaperedPolicy;
pub use nominal_resolution::NominalResolutionPolicy;
pub use perfect_resolution::PerfectResolutionPolicy;
pub use pseudostochastic::PseudostochasticPolicy;
pub use r#trait::StratumRetentionPolicy;
pub use recency_proportional::RecencyProportionalPolicy;
pub use stochastic::StochasticPolicy;
